### ISSUE TITLE
关于setHtml第二个参数高度的疑问

### ISSUE THREAD

**Issue by yinhaijiao** [githubwing/RichTextView#1]
richTextView.setHtml(mTxt, 500);
sample中高度怎样可以不设置？因为富文本具体多高不是一样的呀。

**Comment by githubwing** [comment]
这个不设置高度不行的，因为宽度是给的父布局的宽度，高度的话 可以在parse的时候获取到 再具体设置吧 改下源码

**Comment by yinhaijiao** [comment]
> parse的时候获取到
> 这个是怎么做的？请指教，谢谢。

**Comment by githubwing** [comment]
可以看一下 glideimageGetter源码，里面有个wrapper类，在构造的时候就有传入宽高，最早之前原作者是宽高相等，我给改成宽高不等了

**Comment by yinhaijiao** [comment]
嗯，看到了那个地方的代码，可是这个高度可以动态取么？

**Comment by githubwing** [comment]
一般来说不会解析html里面的宽高吧，因为手机屏幕大小不一样 他们给的是px的  所以还是自己跟着感觉走吧。。一定要获取到的话， 可能要解析html  但是Html.parse好像没有 所以你可以试试jsoup

**Comment by yinhaijiao** [comment]
好难，谢谢了。
